//! Render an `AskRecord` as a self-contained Markdown document with citations.

use serde_json::Value;

use crate::history::AskRecord;

/// Convert an ask record to a Markdown document with numbered footnotes.
pub fn answer_to_markdown(ask: &AskRecord) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Q: {}\n\n", escape(&ask.question)));

    out.push_str(ask.answer.trim());
    out.push_str("\n\n");

    let citations = citations_from(&ask.citations_json);
    if !citations.is_empty() {
        out.push_str("## Citations\n\n");
        for (i, c) in citations.iter().enumerate() {
            let n = i + 1;
            let title = c.section_title.as_deref().unwrap_or("");
            let doc = c.doc_title.as_deref().unwrap_or("");
            let page = c
                .page_range
                .as_ref()
                .map(|(s, _)| format!("page {s}"))
                .unwrap_or_default();
            let header = if title.is_empty() {
                doc.to_string()
            } else {
                format!("{title} from `{doc}`")
            };
            let suffix = if page.is_empty() {
                String::new()
            } else {
                format!(" ({page})")
            };
            out.push_str(&format!("[^{n}]: **{header}**{suffix}\n"));
            if let Some(excerpt) = &c.excerpt {
                for line in excerpt.lines() {
                    out.push_str(&format!("    > {line}\n"));
                }
            }
            out.push('\n');
        }
    }

    out.push_str("---\n");
    out.push_str(&format!(
        "*Generated by recallwell from library `{}` at unix {}*\n",
        ask.library, ask.created_at
    ));
    out
}

struct CitationView {
    doc_title: Option<String>,
    section_title: Option<String>,
    page_range: Option<(u32, u32)>,
    excerpt: Option<String>,
}

fn citations_from(value: &Value) -> Vec<CitationView> {
    let Some(arr) = value.as_array() else {
        return vec![];
    };
    arr.iter()
        .map(|c| CitationView {
            doc_title: c
                .get("doc_title")
                .and_then(|v| v.as_str())
                .map(String::from),
            section_title: c
                .get("section_title")
                .and_then(|v| v.as_str())
                .map(String::from),
            page_range: c.get("page_range").and_then(|v| {
                v.as_array().and_then(|a| {
                    if a.len() == 2 {
                        Some((a[0].as_u64()? as u32, a[1].as_u64()? as u32))
                    } else {
                        None
                    }
                })
            }),
            excerpt: c.get("excerpt").and_then(|v| v.as_str()).map(String::from),
        })
        .collect()
}

fn escape(s: &str) -> String {
    s.replace('\n', " ").trim().to_string()
}

/// Build a filename like `recallwell-<library>-<short>-<date>.md`.
pub fn filename_for(ask: &AskRecord) -> String {
    let short: String = ask
        .question
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect();
    let short = short
        .split('-')
        .filter(|s| !s.is_empty())
        .take(6)
        .collect::<Vec<_>>()
        .join("-");
    let short = if short.is_empty() {
        "ask".into()
    } else {
        short
    };
    let date = chrono_like_date(ask.created_at);
    format!("recallwell-{}-{}-{}.md", ask.library, short, date)
}

fn chrono_like_date(unix_secs: i64) -> String {
    // Minimal date rendering without a chrono dep.
    let secs_per_day = 86_400i64;
    let days_since_epoch = unix_secs / secs_per_day;
    let mut year = 1970i64;
    let mut days = days_since_epoch;
    loop {
        let leap = (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
        let dy = if leap { 366 } else { 365 };
        if days < dy {
            break;
        }
        days -= dy;
        year += 1;
    }
    let leap = (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
    let m = [
        31,
        if leap { 29 } else { 28 },
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31,
    ];
    let mut month = 1i64;
    for &dm in &m {
        if days < dm {
            break;
        }
        days -= dm;
        month += 1;
    }
    let day = days + 1;
    format!("{year:04}-{month:02}-{day:02}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn record_with_citations(citations: Value) -> AskRecord {
        AskRecord {
            id: "01H".into(),
            library: "reading".into(),
            question: "what is consensus?".into(),
            answer: "Consensus is agreement among nodes.\nIt's hard.".into(),
            citations_json: citations,
            trace_json: json!({}),
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn markdown_includes_question_and_answer() {
        let r = record_with_citations(json!([]));
        let md = answer_to_markdown(&r);
        assert!(md.contains("# Q: what is consensus?"));
        assert!(md.contains("Consensus is agreement"));
    }

    #[test]
    fn markdown_renders_footnotes_when_citations_present() {
        let r = record_with_citations(json!([
            {
                "doc_title": "Raft paper",
                "section_title": "Section 5",
                "page_range": [12, 14],
                "excerpt": "A leader is elected each term.",
            }
        ]));
        let md = answer_to_markdown(&r);
        assert!(md.contains("## Citations"));
        assert!(md.contains("[^1]"));
        assert!(md.contains("Section 5"));
        assert!(md.contains("Raft paper"));
        assert!(md.contains("page 12"));
        assert!(md.contains("> A leader is elected each term."));
    }

    #[test]
    fn filename_is_clean() {
        let r = record_with_citations(json!([]));
        let name = filename_for(&r);
        assert!(name.starts_with("recallwell-reading-"));
        assert!(name.ends_with(".md"));
    }
}
